# This is an example from the Revs project.  Objects are not pre-registered, there is one file per object, and a manifest is used.
# Metadata is produced using a mods template.

project_style:
  content_structure:  'simple_image'
  should_register:    true
  get_druid_from:     'suri'

bundle_dir:           '/dor/staging/Revs/PilotProject/content'
staging_dir:          '/dor/assembly'
accession_items:   ~

manifest:             'manifest_craig.csv'
checksums_file:       'output.md5'
desc_md_template:     '../../mods_template.xml'

progress_log_file:    '/dor/preassembly/revs_craig_log.yaml'  
project_name:         'Revs'
apo_druid_id:         'druid:qv648vd4392'
set_druid_id:         'druid:yt502zj0924' # craig set

publish_attr:
  publish:            'no'
  shelve:             'no'
  preserve:           'yes'

compute_checksum:     true
init_assembly_wf:     true

content_md_creation:
  style:              'default'

object_discovery:
  use_manifest:       true
  glob:               ~
  regex:              ~

stageable_discovery:
  use_container:      true
  glob:               ~
  regex:              ~

manifest_cols:
  object_container:   'filename'
  source_id:          'sourceid'
  label:              'label'

content_exclusion:    ~

validate_usage:       true
show_progress:        true
limit_n:              ~
uniqify_source_ids:   false
cleanup:              false
resume:               false
