inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - './Rakefile'
    - './config.ru'
    - '**/*.rb'
    - '**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'config/environments/*.rb'
    - 'config/erubis_monkeypatch.rb' # code essentially copied from rails
    - 'db/**/*'
    - 'vendor/**/*'

Layout/EmptyLineAfterGuardClause: # overkill
  Enabled: false

# rspec expect{...} is conventional
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200
  Exclude:
    - 'config/initializers/**/*.rb' # generated files

RSpec/ContextWording:
  Enabled: false # too dogmatic

# Offense count: 2
RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*.rb' # In view tests, the view is named, not the class

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject: # we use this for `define_enum_for`, `validate_presence_of`, etc.
  Enabled: false

# we like 'expect(x).to receive' better than 'have_received'
RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4 # default: 3

Style/NumericPredicate: # "> 0" is not less readable than ".positive?"
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SymbolArray:
  MinSize: 4
