inherit_from: .rubocop_todo.yml

# rspec expect{...} is conventional
Style/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200
