version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@3.2.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
          executor:
            name: ruby-rails/ruby
            ruby-tag: '3.2.2'
      - ruby-rails/test-rails:
          name: test
          api-only: true # note: this leaves off checking the yarn.lock file, which pre-assembly doesn't have
          executor:
            name: ruby-rails/ruby-postgres
            ruby-tag: '3.2.2'
          before-test:
            - run:
                name: Install exiftool
                command: curl -L http://cpanmin.us | perl - --sudo Image::ExifTool
