version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.0.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
      - ruby-rails/test-rails:
          name: test
          api-only: true # note: this leaves off checking the yarn.lock file, which pre-assembly doesn't have
          before-test:
            - run:
                name: Install exiftool
                command: curl -L http://cpanmin.us | perl - --sudo Image::ExifTool
