version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@4.2.1
  node: circleci/node@5.0.0
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
      - ruby-rails/test-rails:
          name: test
          install-firefox: true
          before-test:
            - run:
                name: Install exiftool
                command: curl -L http://cpanmin.us | perl - --sudo Image::ExifTool
            - run:
                name: Install javascript dependencies and build assets
                command: bin/rake test:prepare
