version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@2.0.0
# NOTE: Jan 2022 TravisCI had this package installed, but tests pass in CircleCI without explicitly adding:
#    - libimage-exiftool-perl
workflows:
  build:
    jobs:
      - ruby-rails/lint:
          name: lint
      - ruby-rails/test-rails:
          name: test
