dor_client_cert:
dor_client_cert_key:

# used to look up object existence in DOR for discovery report
# TODO: can we use dor-services-app instead? (see #226)
fedora_url: 'https://example.com/fedora'

workflow_url: 'https://workflow-env.stanford.edu/workflow'

# place where assemblyWF will look for object files
assembly_staging_dir: tmp/assembly

# writable directory where job run artifacts will live
job_output_parent_dir:  'log/jobs'
