dor_client_cert:
dor_client_cert_key:

# used to make dor-workflow-service call for a druid
#   this is done at end of preassembly to kick off assembly
DOR_SERVICES:
  URL: 'https://example.com/dor/v1'
dor_services_num_attempts: 1 # how many attempts to contact dor before throwing exception

# used to look up object existence in DOR for discovery report
# TODO: can we use dor-services-app instead? (see #226)
fedora_url: 'https://example.com/fedora'

# place where assemblyWF will look for object files
assembly_staging_dir: tmp/assembly

# writable directory where job run artifacts will live
job_output_parent_dir:  'log/jobs'
