# place where assemblyWF will look for object files
assembly_staging_dir: tmp/assembly

# writable directory where job run artifacts will live
job_output_parent_dir:  'log/jobs'

DOR_SERVICES:
  URL: 'http://localhost:3003'
  TOKEN: 'secret-token'


workflow_url: 'https://workflow-env.stanford.edu/workflow'
workflow:
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'
  timeout: 60
