# place where assemblyWF will look for object files
assembly_staging_dir: tmp/assembly

# writable directory where job run artifacts will live
job_output_parent_dir:  'log/jobs'

dor_services:
  url: 'http://localhost:3003'
  token: 'secret-token'

expected_worker_count: 5 # for okcomputer endpoint

mailer_host: 'localhost'
repository_manager_email: CHANGE_ME@stanford.edu

redis_url: redis://localhost:6379/

workflow_url: 'http://localhost:3002'

workflow:
  timeout: 60

rabbitmq:
  enabled: false
  hostname: localhost
  vhost: /
  username: guest
  password: guest

